using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using AppointIn.Data;
using AppointIn.Domain.Entities;

namespace AppointIn.TestDataSeed
{
	public static partial class DataInitializer
	{

		public static ICollection<Address> GenerateAddresses()
		{
			var newAddresses = new List<Address>()
			{
				new Address() { StreetName = "Obere Str. 57", PostalCode = "12209", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Berlin").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Avda. de la Constitución 2222", PostalCode = "05021", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "CDMX").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Mataderos 2312", PostalCode = "05023", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "CDMX").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "120 Hanover Sq.", PostalCode = "WA1 1DP", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "London").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Berguvsvägen 8", PostalCode = "S-958 22", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Luleå").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Forsterstr. 57", PostalCode = "68306", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Mannheim").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "24, place Kléber", PostalCode = "67000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Strasbourg").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "C/ Araquil, 67", PostalCode = "28023", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Madrid").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "12, rue des Bouchers", PostalCode = "13008", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Marseille").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "23 Tsawassen Blvd.", PostalCode = "T2F 8M4", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Tsawassen").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Fauntleroy Circus", PostalCode = "EC2 5NT", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "London").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Cerrito 333", PostalCode = "1010", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Buenos Aires").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Sierras de Granada 9993", PostalCode = "05022", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "CDMX").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Hauptstr. 29", PostalCode = "3012", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Bern").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Av. dos Lusíadas, 23", PostalCode = "05432-043", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "São Paulo").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Berkeley Gardens 12 Brewery ", PostalCode = "WX1 6LT", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "London").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Walserweg 21", PostalCode = "52066", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Aachen").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "67, rue des Cinquante Otages", PostalCode = "44000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Nantes").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "35 King George", PostalCode = "WX3 6FW", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "London").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Kirchgasse 6", PostalCode = "8010", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Graz").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Rua Orós, 92", PostalCode = "05442-030", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "São Paulo").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "C/ Moralzarzal, 86", PostalCode = "28034", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Madrid").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "184, chaussée de Tournai", PostalCode = "59000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Lille").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Åkergatan 24", PostalCode = "S-844 67", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Bräcke").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Berliner Platz 43", PostalCode = "80805", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "München").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "54, rue Royale", PostalCode = "44000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Nantes").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Via Monte Bianco 34", PostalCode = "10100", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Torino").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Jardim das rosas n. 32", PostalCode = "1675", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Lisboa").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Rambla de Cataluña, 23", PostalCode = "08022", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Barcelona").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "C/ Romero, 33", PostalCode = "41101", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Sevilla").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Av. Brasil, 442", PostalCode = "04876-786", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Campinas").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "2732 Baker Blvd.", PostalCode = "97403", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Eugene").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "5ª Ave. Los Palos Grandes", PostalCode = "1081", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Caracas").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Rua do Paço, 67", PostalCode = "05454-876", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Rio de Janeiro").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Carrera 22 con Ave. Carlos Soublette #8-35", PostalCode = "5022", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "San Cristóbal").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "City Center Plaza 516 Main St.", PostalCode = "97827", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Elgin").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "8 Johnstown Road", PostalCode = "", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Cork").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Garden House Crowther Way", PostalCode = "PO31 7PJ", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Cowes").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Maubelstr. 90", PostalCode = "14776", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Brandenburg").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "67, avenue de lEurope", PostalCode = "78000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Versailles").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "1 rue Alsace-Lorraine", PostalCode = "31000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Toulouse").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "1900 Oak St.", PostalCode = "V3F 2K1", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Vancouver").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "12 Orchestra Terrace", PostalCode = "99362", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Walla Walla").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Magazinweg 7", PostalCode = "60528", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Frankfurt a.M. ").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "87 Polk St. Suite 5", PostalCode = "94117", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "San Francisco").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Carrera 52 con Ave. Bolívar #65-98 Llano Largo", PostalCode = "3508", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Barquisimeto").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Ave. 5 de Mayo Porlamar", PostalCode = "4980", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "I. de Margarita").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "89 Chiaroscuro Rd.", PostalCode = "97219", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Portland").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Via Ludovico il Moro 22", PostalCode = "24100", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Bergamo").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Rue Joseph-Bens 532", PostalCode = "B-1180", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Bruxelles").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "43 rue St. Laurent", PostalCode = "H1J 1C3", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Montréal").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Heerstr. 22", PostalCode = "04179", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Leipzig").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "South House 300 Queensbridge", PostalCode = "SW7 1RZ", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "London").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Ing. Gustavo Moncada 8585 Piso 20-A", PostalCode = "1010", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Buenos Aires").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "2743 Bering St.", PostalCode = "99508", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Anchorage").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Mehrheimerstr. 369", PostalCode = "50739", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Köln").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "265, boulevard Charonne", PostalCode = "75012", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Paris").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Calle Dr. Jorge Cash 321", PostalCode = "05033", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "CDMX").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Geislweg 14", PostalCode = "5020", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Salzburg").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Estrada da saúde n. 58", PostalCode = "1756", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Lisboa").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Rua da Panificadora, 12", PostalCode = "02389-673", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Rio de Janeiro").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Alameda dos Canàrios, 891", PostalCode = "05487-020", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "São Paulo").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Taucherstraße 10", PostalCode = "01307", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Cunewalde").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Av. del Libertador 900", PostalCode = "1010", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Buenos Aires").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "2817 Milton Dr.", PostalCode = "87110", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Albuquerque").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Strada Provinciale 124", PostalCode = "42100", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Reggio Emilia").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Av. Copacabana, 267", PostalCode = "02389-890", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Rio de Janeiro").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Grenzacherweg 237", PostalCode = "1203", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Genève").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Gran Vía, 1", PostalCode = "28001", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Madrid").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Erling Skakkes gate 78", PostalCode = "4110", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Stavern").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "187 Suffolk Ln.", PostalCode = "83720", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Boise").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "90 Wadhurst Rd.", PostalCode = "OX15 4NB", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "London").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Vinbæltet 34", PostalCode = "1734", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "København").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "25, rue Lauriston", PostalCode = "75016", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Paris").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "P.O. Box 555", PostalCode = "82520", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Lander").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Boulevard Tirou, 255", PostalCode = "B-6000", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Charleroi").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "89 Jefferson Way Suite 2", PostalCode = "97201", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Portland").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "55 Grizzly Peak Rd.", PostalCode = "59801", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Butte").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Luisenstr. 48", PostalCode = "44087", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Münster").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Avda. Azteca 123", PostalCode = "05033", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "CDMX").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Av. Inês de Castro, 414", PostalCode = "05634-030", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "São Paulo").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "722 DaVinci Blvd.", PostalCode = "98034", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Kirkland").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Smagsløget 45", PostalCode = "8200", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Århus").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "2, rue du Commerce", PostalCode = "69004", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Lyon").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "59 rue de lAbbaye", PostalCode = "51100", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Reims").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Adenauerallee 900", PostalCode = "70563", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Stuttgart").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Torikatu 38", PostalCode = "90110", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Oulu").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Rua do Mercado, 12", PostalCode = "08737-363", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Resende").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "305 - 14th Ave. S. Suite 3B", PostalCode = "98128", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Seattle").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "Keskuskatu 45", PostalCode = "21240", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Helsinki").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" },
				new Address() { StreetName = "ul. Filtrowa 68", PostalCode = "01-012", Phone = "", City = UnitOfWork.Data.Cities.GetAll().Where(city => city.Name == "Walla").FirstOrDefault(), CreateDate = DateTime.Now.ToUniversalTime(), CreatedBy ="DataInitializer", LastUpdateBy = "DataInitializer" }
			};

			return newAddresses;
		}


		// Using lambda expression to simplify call to an object property's method
		public static bool DataBaseHasInitializedAddresses()
			=> UnitOfWork.Data.Addresses.GetAll().Any();
	}
}
