//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointIn.DesktopApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppointIn.DesktopApp.Resources.DashboardFormStrings", typeof(DashboardFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments per Month....
        /// </summary>
        internal static string AppointmentsPerMonthReportMenuButtonText {
            get {
                return ResourceManager.GetString("AppointmentsPerMonthReportMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Summary by Country...
        ///.
        /// </summary>
        internal static string CustomerCountrySummaryMenuButtonText {
            get {
                return ResourceManager.GetString("CustomerCountrySummaryMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Addresses.
        /// </summary>
        internal static string ManageAddressesMenuButtonText {
            get {
                return ResourceManager.GetString("ManageAddressesMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Appointments.
        /// </summary>
        internal static string ManageAppointmentsMenuButtonText {
            get {
                return ResourceManager.GetString("ManageAppointmentsMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cities.
        /// </summary>
        internal static string ManageCitiesMenuButtonText {
            get {
                return ResourceManager.GetString("ManageCitiesMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Countries.
        /// </summary>
        internal static string ManageCountriesMenuButtonText {
            get {
                return ResourceManager.GetString("ManageCountriesMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Customers.
        /// </summary>
        internal static string ManageCustomersMenuButtonText {
            get {
                return ResourceManager.GetString("ManageCustomersMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Records.
        /// </summary>
        internal static string ManageRecordsMenuButtonText {
            get {
                return ResourceManager.GetString("ManageRecordsMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsMenuButtonText {
            get {
                return ResourceManager.GetString("ReportsMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Appointments.
        /// </summary>
        internal static string UpcomingAppointmentsLabelText {
            get {
                return ResourceManager.GetString("UpcomingAppointmentsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for Users....
        /// </summary>
        internal static string UserScheduleReportMenuButtonText {
            get {
                return ResourceManager.GetString("UserScheduleReportMenuButtonText", resourceCulture);
            }
        }
    }
}
